apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-ingerencia-ng
  name: ms-ingerencia-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-ingerencia-ng
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/my_docker_network: "true"
        io.kompose.service: ms-ingerencia-ng
    spec:
      containers:
      - image: krisaor/linux-academy:java1.0.0.RELEASE
        imagePullPolicy: ""
        name: ms-ingerencia-ng
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
